server:
  port: 8080

spring:
  application:
    name: blog-app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:blog_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_STATUS:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

jwt:
  secret: ${JWT_SECRET:14e493e2c9aa4a805f63c57895e3332d134794af68d624f48c99c04a3d757444}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}        # 15 mins
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}    # 7 days